### ISSUE TITLE
Remove Obj and Bin folders and their contents

### ISSUE THREAD

**Issue by ericwood8** [tbarracha/Angspire#1]
I love what you attempting with the overall repo.  Minor thing - Remove Obj and Bin folders and their contents from all the various projects in the solution.  Visual Studio creates these when it compiles.  It will reduce file size and speed up cloning/downloads.  Read about .gitignore to prevent from happening in the future.

**Comment by tbarracha** [comment]
Hello! Thank you for spotting the oversight! I was using the wrong .gitignore. It is now updated for both Angular and DotNet
Please confirm if its solved
